import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Exo_2 } from "next/font/google";
import "./Global.scss";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });
const exo2 = Exo_2({
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="synthwave">
      <body className={`${exo2.className} min-h-screen flex-col`}>
        <div className="flex flex-col h-screen justify-between">
          <header>
            <Navbar></Navbar>
          </header>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
